- .env.example
- .gitignore
- index.html
- package.json
- src/App.css
- src/components/Chip.tsx
- src/components/SearchBar.tsx
- src/page/Map/_components/SearchHeader.tsx
- src/page/Map/_components/SearchInput.tsx
- src/page/Map/index.tsx
- src/vite-env.d.ts
- tsconfig.json
- yarn.lock
> Feat - Basic map view

- src/components/NavBar.tsx
- src/page/Map/index.tsx
> ex) * #15
> navbar 너비 변경, 스크롤 인식문제 해결
> Fix navbar width

- src/Layout.tsx
- src/components/NavBar.tsx
> #15
> layout 너비 최소 320px ~ 최대 440px 로 변경
> [Style] Layout style setting

- src/App.css
- src/components/buttons/Button.tsx
- src/style/font.ts
- yarn.lock
> #22 
- 버튼 수정
- font 수정
- App 사이즈 수정
> [Feat] Setting

- db.json
- package.json
- src/hooks/useMapSetup.tsx
- src/main.tsx
- src/page/Map/_components/Restaurant.tsx
- src/page/Map/index.tsx
- yarn.lock
> ex) * #30
> json server, react query 추가
>
> [Feat] json server & react query

- package.json
- src/Layout.tsx
- src/components/Toast.tsx
- src/page/Landing/index.tsx
- src/store/index.ts
- src/store/toastStore.ts
- src/utils/toastPopup.ts
- yarn.lock
> #28
> 전역 상태 관리 라이브러리 zustand 설치
layout 부분에 토스트 설정
landing page 에 토스트 팝업이 뜨는 예시 버튼 생성
토스트 팝업 리팩토링
> [Feat] Toast

- src/page/Map/_components/ImageSwiper.tsx
#3 
ImageSwiper의 image radius 12px -> 8px로 수정
> [style] Change place image radius

- src/components/Button.tsx
- src/style/GlobalStyle.ts
> [Style] - style change

- src/components/SearchBar.tsx
> 수연님 요청에 따른 search bar place holder font size 수정(B2 -> B3)
> [Style] change font size

- src/Layout.tsx
- src/components/Modal.tsx
- src/page/Contents/index.tsx
- src/page/Profile/Profile.tsx
- src/store/index.ts
- src/store/modalStore.ts
- src/utils/modalPopup.ts
> ex) * #70
> 모달 컴포넌트에 후크와 스토어 적용
> contents 페이지에 예시 사용법 구현
```
const { openModal, closeModal } = useModalPopup();
const modalData: ModalProps = {
type: "ok",
title: "확인 모달",
body: ["이 모달은", "확인만 있어요!"],
okButtonText: "확인",
onOkButtonClick: () => {
closeModal();
},
};
const okModal = () => {
openModal(modalData);
};
const cancelOkModal = () => {
openModal({
type: "cancel-ok",
title: "취소와 확인 모달",
body: ["이 모달에는", "확인과 취소가 있어요!"],
okButtonText: "확인",
onOkButtonClick: () => {
closeModal();
},
cancelButtonText: "취소",
onCancelButtonClick: () => {
closeModal();
},
});
};
return (
<div style={{ position: "relative", width: "100%" }}>
<button onClick={okModal}>정보 확인 모달</button>
<button onClick={cancelOkModal}>의사 확인 모달</button>
</div>
);
```
> [Feat] Update modal

- src/page/OtherProfile/_components/ProfileReview.tsx
- src/page/OtherProfile/_components/RequestButton.tsx
- src/page/OtherProfile/index.tsx
- src/routes/route.tsx
> #68 
> 다른사람의 프로필을 볼 때 필요한 컴포넌트들 생성.
> [Feat] Create other's profile components

- src/api/Interceptor.ts
- src/api/errorCodes.ts
- src/api/errorHandler.ts
> [Fix] Interceptor 변경 및 에러코드 추가

- src/api/getApi.ts
- src/api/postApi.ts
- src/hooks/api/review/useGetSearchPlaces.ts
- src/hooks/api/review/usePostCreateReview.ts
- src/interface/apiInterface.ts
- src/page/Review/_components/DatePick/DatePick.tsx
- src/page/Review/_components/PlaceSearch/PlaceSearch.tsx
- src/page/Review/_components/PlaceSearch/ReviewSearchBar.tsx
- src/page/Review/_components/PlaceSearch/SearchResult.tsx
- src/page/Review/_components/PlaceSearch/SearchedPlace.tsx
- src/page/Review/_components/ReviewTotal/PlaceInfo.tsx
- src/page/Review/_components/ReviewTotal/ReviewTotal.tsx
- src/page/Review/index.tsx
> [Feat] Review Fetching 

- src/api/postApi.ts
- src/hooks/api/review/usePostCreateReview.ts
- src/interface/apiInterface.ts
- src/page/Review/_components/ReviewTotal/PhotoUpload.tsx
- src/page/Review/_components/ReviewTotal/ReviewTotal.tsx
> 리뷰 업로드 시 타입 string -> form data
> feat - review data photo upload type change

- src/api/getApi.ts
- src/components/SearchBar.tsx
- src/hooks/api/useGetPlaces.ts
- src/hooks/useUpdatePlaces.ts
- src/interface/apiInterface.ts
- src/page/Map/_components/ImageSwiper.tsx
- src/page/Map/_components/Restaurant.tsx
- src/page/Map/_components/headers/SearchHeader.tsx
- src/page/Map/index.tsx
> feat - data syncronize for review tab in Map

- src/api/getApi.ts
- src/hooks/api/review/usePostCreateReview.ts
- src/hooks/api/useGetSpecificPlace.ts
- src/interface/apiInterface.ts
- src/page/Map/_components/Restaurant.tsx
- src/page/Map/_components/headers/ReviewHeader.tsx
- src/page/Map/_components/review/Review.tsx
- src/page/Map/_components/review/ReviewSingle.tsx
- src/page/Map/index.tsx
- src/page/MyPlace/_components/FilterHead.tsx
- src/page/MyPlace/_components/Header.tsx
- src/page/MyPlace/_components/RestaurantBoxForm.tsx
- src/page/MyPlace/index.tsx
- src/page/Review/_components/ReviewTotal/CompleteModal.tsx
- src/page/Review/_components/ReviewTotal/ReviewTotal.tsx
> [Feat] - review almost finish, navigate to map

- src/hooks/api/review/usePostCreateReview.ts
- src/page/Review/_components/ReviewTotal/CompleteModal.tsx
- src/page/Review/_components/ReviewTotal/ReviewTotal.tsx
- src/page/Review/index.tsx
> 리뷰 작성 및 접속 플로우 끝. 데이터 연동 한 부분 남음
> [Feat] - review flow end

- src/api/getApi.ts
- src/hooks/api/useGetSpecificPlace.ts
- src/interface/apiInterface.ts
- src/page/Map/_components/review/GraphBar.tsx
- src/page/Map/_components/review/Review.tsx
- src/page/Map/_components/review/ReviewGraph.tsx
- src/page/Map/_components/review/ReviewSingle.tsx
- src/page/Map/index.tsx
- src/page/Review/_components/ReviewTotal/ReviewTotal.tsx
- src/style/font.ts
> [Feat] Review Graph add

- src/api/getApi.ts
- src/components/SearchBar.tsx
- src/hooks/useMapSetup.ts
- src/interface/member.ts
- src/interface/review.ts
- src/page/Map/_components/headers/SearchHeader.tsx
- src/page/Map/index.tsx
- src/page/Profile/Profile.tsx
- src/page/Profile/_components/reviews/ReviewHistory.tsx
- src/page/Profile/_components/reviews/ReviewText.tsx
- src/page/SignUp/_components/stages/Welcome.tsx
> [Feat] Map & Feedapi

- src/page/Map/_components/headers/ReviewHeader.tsx
- src/page/Map/index.tsx
> ex) * #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> feat - myPlace feature

- vercel.json
> fix - vercel error fixing

- src/api/getApi.ts
- src/hooks/api/myPlace/useGetMyPlace.ts
- src/hooks/api/pinbuddySearch/useGetSearchPinbuddy.ts
- src/hooks/api/useGetSpecificPlace.ts
- src/interface/apiInterface.ts
- src/page/Map/_components/headers/ReviewHeader.tsx
- src/page/Map/_components/review/Review.tsx
- src/page/Map/index.tsx
- src/page/MyPlace/_components/RestaurantBoxForm.tsx
- src/page/MyPlace/index.tsx
- src/page/PinbuddySearch/index.tsx
- src/page/Review/_components/PlaceSearch/SearchResult.tsx
- src/page/Review/_components/ReviewTotal/ReviewTotal.tsx
> Myplace luke

- src/page/Map/index.tsx
> ex) * #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> feat - map feature

- src/api/postApi.ts
- src/hooks/api/pinbuddySearch/usePostFriendRequest.ts
- src/page/PinbuddySearch/_components/SearchResultSingle.tsx
> ex) * #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> fix :  friend request complete

- src/utils/getFromLocalStorage.ts
> Default coords from last known position

- src/hooks/useMapSetup.ts
- src/page/Map/index.tsx
> Map default coords

- package.json
- vite.config.ts
- yarn.lock
> Add sentry

- package.json
- src/App.tsx
- src/SentryInit.js
- src/SentryInit.ts
- src/main.tsx
- vite.config.ts
- yarn.lock
> ex) * #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> Configure Sentry
